### ISSUE TITLE
Enhancement: generic s3 compatible storage 

### ISSUE THREAD

**Issue by buzzzo** [gilbertchen/duplicacy#85] opened 2017-07-02 20:33 UTC
Would be useful to add generic s3 compatible storage so any cloud provider which implements s3 compatible api should work.

**Comment by gilbertchen** [comment] 2017-07-03 00:39
The s3 storage backend is based on the official Amazon S3 client library: https://github.com/aws/aws-sdk-go.  It may work with other s3 compatible storages like wasabi.com.

What is the s3 compatible storage that you intend to use?

**Comment by buzzzo** [comment] 2017-07-03 08:19
Hi
I'm using cynnaspace, an italian cloud storage provider.
I'm able to perform backups with cloudberry software, which have a plain s3 compatible storage support (and also s3 NATIVE support).

When i ran the init command:
duplicacy init backup_name s3://default@cs2.cynnyspaces3.com/BUCKET

I receive the following error:
ailed to configure the storage: InvalidAccessKeyId: The AWS access key Id you provided does not exist in our records.
	status code: 403, request id: , host id:
NOTE: i have specified the region default to workaround the fact that duplicacy require me to specify the region name.

Thx

**Comment by gilbertchen** [comment] 2017-07-04 04:00
I suspect this could be an issue of V2 signing vs V4 signing.  aws-sdk-go only supports V4.  Does cynnyspace have any documentation on their website that talks about which version they are using?  You can also try Duplicacy 2.0.2 to see if it works with cynnyspace.  Until that version the S3 storage backend was written with [go-amz](https://github.com/goamz/goamz) which support only V2.

**Comment by buzzzo** [comment] 2017-07-04 08:15
Yes, they support ONLY  v2 signing.
I've the same problem with cloudberry (which support btw both v2 and v4).
Any plan to re-introduce in newer version the v2 signing ?

Thx for help

**Comment by gilbertchen** [comment] 2017-07-04 13:14
I'm thinking about adding back the old go-amz code, but making it a separate backend called s3c.

Does 2.0.2 work with cynnyspace?

**Comment by buzzzo** [comment] 2017-07-04 13:23
Yes it's works.
Thx

**Comment by flibustenet** [comment] 2017-07-11 07:31
I couldn't make it work with http://minio.io it give me 
`Failed to download the configuration file from the storage: MissingRegion: could not find region configuration`

And when i use `s3://us-east-1@bck:9000/duplicacy` nothing append.

**Comment by Kidswiss** [comment] 2017-07-11 15:27
I have a similar problem. I'm trying to use minio with duplicacy and when i enter my url like:
`s3//us-east-1@mydomain.com/test`
It won't connect with follow error:
`Failed to download the configuration file from the storage: RequestError: send request failed
caused by: Head https://test.mydomain.com/config: dial tcp: lookup test.mydomain.com: no such host`

Why does it use the bucket name as a subdomain name?

**Comment by gilbertchen** [comment] 2017-07-11 17:49
I checked in a change (https://github.com/gilbertchen/duplicacy/commit/f8764a5a79067f9e57a3c577cbe8c3a7a319f4ab) that makes the s3 storage backend work with minio.  Just use the storage url prefix `minio`:

```
duplicacy init test minio://us-east-1@127.0.0.1:9000/duplicacy
/repository will be backed up to minio://us-east-1@127.0.0.1:9000/duplicacy with id test
```

**Comment by flibustenet** [comment] 2017-07-11 20:14
I can confirm that it works with minio (init, backup, restore).

**Comment by gilbertchen** [comment] 2017-07-12 00:34
Thanks.  Under the hood, `minio://` still uses the the amazon s3 storage backend but turns on the minio compatibility mode.  It was basically a two line change:

```
S3ForcePathStyle: aws.Bool(isMinioCompatible),
DisableSSL: aws.Bool(isMinioCompatible),
```

The first line avoids adding the bucket name to the endpoint url, and the second line disables SSL.

Now I'll make a s3c backend using the old go-amz code to support those s3 compatible storages that require V2 Signing.

**Comment by gilbertchen** [comment] 2017-07-12 01:48
The latest commit (https://github.com/gilbertchen/duplicacy/commit/f8d879d41454e6a9bddb408f25bc4bb750aca436) reintroduced the old  [go-amz](https://github.com/goamz/goamz)-based s3 backend with the storage url prefix `s3c://`.  @buzzzo can you check if it works with cynnyspace?

**Comment by Kidswiss** [comment] 2017-07-12 09:16
I can confirm it works without SSL. But my minio server is secured via SSL/TLS:

`Failed to configure the storage: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
status code: 403, request id: 14D08A7DB79361C0, host id: `

It seems that you completely disable SSL/TLS when using `minio://`. How about `minio://` for unencrypted traffic and `minios://` with SSL/TLS enabled?

**Comment by gilbertchen** [comment] 2017-07-13 01:23
Commit https://github.com/gilbertchen/duplicacy/commit/483ae5e6eb161e6262539e90870e3e8a7893f3be added the `minios://` storage.

**Comment by Kidswiss** [comment] 2017-07-13 08:07
Thank you for the quick implementation!

But it seems that there's still a problem. Now if i use `minios://`and enter my credentials it will hang indefinitely. A quick look in my server logs shows that  it doesn't even contact my webserver.

**Comment by Kidswiss** [comment] 2017-07-13 19:43
Huh, when I just tried to reproduce the issue and it suddenly worked! Very strange.

**Comment by gilbertchen** [comment] 2017-07-13 21:17
It also worked in my test, so there might be something else wrong in your first try.

**Closed** 2017-09-17 03:51 UTC
Labels: enhancement
