### ISSUE TITLE
Error: the chunk XXX has a hash id of YYY

### ISSUE THREAD

**Issue by joostn** [gilbertchen/duplicacy#89] opened 2017-07-05 14:16 UTC
Hi,

I'm running into this error:

```
D:\>duplicacy prune -keep 0:360 -keep 30:180 -keep 7:30 -keep 1:7
Storage set to b2://joostn-duplicacy
Keep no snapshots older than 360 days
Keep 1 snapshot every 30 day(s) if older than 180 day(s)
Keep 1 snapshot every 7 day(s) if older than 30 day(s)
Keep 1 snapshot every 1 day(s) if older than 7 day(s)
Deleting snapshot drive_d at revision 2
Deleting snapshot drive_d at revision 3
The chunk 3d34cf8eccf91a86ea3eed1406fec5af57109c1d2a803712d4b2b686ef5b035b load from the snapshot cache has a hash id of d025262804ff6698155404d6a06791a9c3a30c497624b89baff2b9a9cda7cc0e
The chunk 3d34cf8eccf91a86ea3eed1406fec5af57109c1d2a803712d4b2b686ef5b035b has a hash id of d025262804ff6698155404d6a06791a9c3a30c497624b89baff2b9a9cda7cc0e
```

duplicacy check returns the same error. I'm running version 2.0.3 on Windows 10.

Any ideas what might cause this and how to resolve it?

**Comment by gilbertchen** [comment] 2017-07-05 15:39
Not sure if this was caused by a Duplicacy bug or a corrupted file in the local cache.  You can locate the chunk file 3d34... under <repository>/.duplicacy/cache and remove that file.  If the same error happens to other chunks then remove the entire <repository>/.duplicacy/cache directory.

Once you are able to run the check command you should run it with the -a and -files options to make sure all backups are good, but beware this will cause a lot of download traffic.

**Comment by gilbertchen** [comment] 2017-07-05 15:52
Forgot to mention that you only need to run the check command on backups that have not been checked before.  All files stored on the storage are immutable (with the exception of the file 'config' which may be re-written by the password command), so there is really no need to re-check a backup at the file level unless you don't trust the storage service.  On the other hand, it may be a good idea to run the check command without the -files option after each prune command, just to guard against any bug in the two-step fossil collection algorithm.  Checking without the -files option will only list chunk files so it is not traffic-intensive.

**Comment by joostn** [comment] 2017-07-05 16:40
Thanks for the quick reply. I've deleted the chunk, but 'duplicacy check' (without any options) downloads it again and reports the same error. 

The file contents starts with this:

`17eee51a68b5fe9a3a58aa0e1bf8289367995504f5ef","e4a4fa3cc5140ada71a893fbbc7616e55c43101d3590cb4d503d295df56964a6","b7be2880c49a9203e923cfe9811b34c3a0e15500556c8d9eaaa35cf12a0a7159","ab00edfd03036f75da230cb1300bad1e18acc8d127e18403544557f68733f726","f7fc120de28d3e01e728920e4871b8c906197e14a4347e54db49847f610c5463","f2f4f22acf06f318320310fa97253b0efd285cc5fbf3ed43a41287130b3f54ba","93e469406358c00135c11c1af35da2bb12accbd2a0bb54d9e9d450c38aca7255",.....]
`

So it's a JSON array but somehow the beginning of the file got lost, the opening bracket is missing. 
I could delete the remote file but I'm afraid this would further corrupt the backup.

**Comment by gilbertchen** [comment] 2017-07-05 17:20
Can you run `duplicacy check -r revision_number` on each revision one by one to see which revision has the issue?  Is version 2.0.3 the only version you've ever run?

**Comment by gilbertchen** [comment] 2017-07-05 17:24
The file content looks ok. It is not a complete json file by itself but with other chunks combined it will be complete.

**Comment by joostn** [comment] 2017-07-06 08:08
`Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\joostn>d:

D:\>duplicacy list
Storage set to b2://joostn-duplicacy
Snapshot drive_d revision 1 created at 2017-06-27 18:59 -hash -vss
Snapshot drive_d revision 2 created at 2017-06-28 09:42 -vss
Snapshot drive_d revision 3 created at 2017-06-28 12:59 -vss
Snapshot drive_d revision 4 created at 2017-06-29 22:33 -vss
Snapshot drive_d revision 5 created at 2017-06-30 14:10 -vss
Snapshot drive_d revision 6 created at 2017-07-02 14:10 -vss
Snapshot drive_d revision 7 created at 2017-07-03 14:10 -vss

D:\>duplicacy check -r 1
Storage set to b2://joostn-duplicacy
Listing all chunks
All chunks referenced by snapshot drive_d at revision 1 exist

D:\>duplicacy check -r 7
Storage set to b2://joostn-duplicacy
Listing all chunks
The chunk 3d34cf8eccf91a86ea3eed1406fec5af57109c1d2a803712d4b2b686ef5b035b has a hash id of d025262804ff6698155404d6a06791a9c3a30c497624b89baff2b9a9cda7cc0e

D:\>duplicacy check -r 6
Storage set to b2://joostn-duplicacy
Listing all chunks
All chunks referenced by snapshot drive_d at revision 6 exist

D:\>duplicacy backup -vss -threads 1
Storage set to b2://joostn-duplicacy
The chunk 3d34cf8eccf91a86ea3eed1406fec5af57109c1d2a803712d4b2b686ef5b035b has a hash id of d025262804ff6698155404d6a06791a9c3a30c497624b89baff2b9a9cda7cc0e
`
So the error seems to be in the latest revision only. New backups are failing because of this error.

It might be a coincidence, but I think the error appeared after the first time 'duplicacy prune -keep 0:360 -keep 30:180 -keep 7:30 -keep 1:7' actually started to delete revisions. I've only used version 2.0.3.

Shall I do 'duplicacy prune -r 7' ?

**Comment by gilbertchen** [comment] 2017-07-06 16:14
I am afraid 'duplicacy prune -r 7' will give the same error.  You'll have to manually delete the snapshot file `snapshots/drive_d/7` from the storage, and then run this prune command to clean up the storage assuming no other backups are running at the same time:

```
duplicacy prune -d -exclusive -exhaustive     # dry-run
duplicacy prune -exclusive -exhaustive          # remove all unreferenced chunks
```

After that, you should run `duplicacy check --files` to verify all backups.

Are your backups encrypted?  If not, would you mind sending me the chunk file 3d34cf... as well as the snapshot file snapshots/drive_d/7 for analysis?  These files contain only chunk hashes and won't expose any information about the stored files.

**Comment by joostn** [comment] 2017-07-07 07:59
Ok, thanks, that seems to have fixed the problem. I'll rather do a full restore to verify the backup (but it's 600G).

The backup is encrypted but if I can unencrypt the chunks myself I'd be happy to help. My email address in in my git profile.

**Comment by gilbertchen** [comment] 2017-07-07 17:32
```
The chunk 3d34cf8eccf91a86ea3eed1406fec5af57109c1d2a803712d4b2b686ef5b035b load from the snapshot cache has a hash id of d025262804ff6698155404d6a06791a9c3a30c497624b89baff2b9a9cda7cc0e
```
This log line means the chunk was saved to the snapshot cache during the backup at revision 7.  So either there is a bug in chunk id calculation or the chunk content somehow changed between the id calculation and the file writing.

For version 2.0.5 an extra check is added before saving the chunk to verify that the id is correct. This change will catch the error much earlier and give the user a chance to rerun the backup.  And it only applies to snapshot chunks so it won't have much impact on the performance.

I'll close this issue for now but will reopen it if this bug emerges again.

**Closed** 2017-07-07 17:33 UTC
Labels: bug
