### ISSUE TITLE
Linux not saving passwords

### ISSUE THREAD

**Issue by nikjft** [gilbertchen/duplicacy#166] opened 2017-09-07 02:06 UTC
I initialized a new repo with a simple "duplicacy init -e my-snapshot b2://my-bucket", went through the song and dance of passwords and whatnot. When I then ran a backup, it asked for passwords again.

Using a basic Ubuntu configuration and I have gnome-keyring installed. How would I go about troubleshooting this?

**Comment by gilbertchen** [comment] 2017-09-07 02:25
Run `duplicacy -d list` to see if it complains about any issue on getting passwords from gnome-keyring.

**Comment by flamingm0e** [comment] 2017-09-07 03:34
I saw something similar.  I wound up putting the env variables in my zshrc.  I will remove these and do some testing if you would like.

Fedora 26, GNOME Desktop

**Comment by gilbertchen** [comment] 2017-09-07 19:22
This is a duplicate of #103

**Closed by gilbertchen** 2017-09-07 19:22 UTC
Labels: duplicate
