### ISSUE TITLE
Restore syntax is wrong when using multiple threads in Mac GUI 

### ISSUE THREAD

**Issue by nikjft** [gilbertchen/duplicacy#119] opened 2017-08-23 22:10 UTC
When restoring a file and multiple threads are selected, it sends the following CLI command:

duplicacy -background -log  restore -r 1 -overwrite -- "foo.txt"  -threads 4

Since the -threads is at the end of the command, the pattern is ignored and the whole repo is downloaded.

Syntax should be:

duplicacy -background -log  restore -r 1  -threads 4 -overwrite -- "foo.txt"

**Comment by gilbertchen** [comment] 2017-08-24 03:26
This is a bug caused by a change in version 2.0.7 to honor the threads option when running the restore command.  Only the GUI version is affected.

Version 2.0.8 available from https://duplicacy.com should fix this bug.

**Comment by TheBestPessimist** [comment] 2017-08-24 10:03
I can confirm that this is fixed in 2.0.8

**Closed** 2017-08-27 01:06 UTC
Labels: bug, GUI
